
language: node_js
# docker cannot be run on osx in travis
os: linux
addons:
  apt:
    packages:
      - vagrant
      - virtualbox
      - genisoimage
node_js: 
  - "12"
install: npm install && npm link
script: slim build images/alpine3.8-simple && slim images
